name: Nuget

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Pack nuget packages
      run: |
        Get-Location
        cd packaging
        Get-Location
