name: Push to azure nuget feed

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - name: Nuget pack
      working-directory: .\packaging
      run: |
        gci -Path AIGirl -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.AIGirl.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.AIGirl.$($_.BaseName);gameVersion=2020.05.29.1;unityVersion=2018.2.21.2"; }
        gci -Path AIShoujo -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.AIShoujo.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.AIShoujo.$($_.BaseName);gameVersion=2019.12.20.1;unityVersion=2018.2.21.2"; }
        gci -Path EmotionCreators -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.EmotionCreators.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.EmotionCreators.$($_.BaseName);gameVersion=2019.6.6.1;unityVersion=2017.4.24.2"; }
        gci -Path Koikatu -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.Koikatu.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.Koikatu.$($_.BaseName);gameVersion=2019.4.27.1;unityVersion=5.6.2.1"; }
        gci -Path KoikatsuParty -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.KoikatsuParty.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.KoikatsuParty.$($_.BaseName);gameVersion=2019.4.27.1;unityVersion=5.6.2.1"; }
        gci -Path PlayHome -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.PlayHome.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.PlayHome.$($_.BaseName);gameVersion=2018.3.11.1;unityVersion=5.5.5.1"; }
        gci -Path HoneySelect -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.HoneySelect.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName-properties "id=IllusionLibs.HoneySelect.$($_.BaseName);gameVersion=2017.6.30.1;unityVersion=5.3.5.1"; }
        gci -Path HoneySelect2 -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.HoneySelect2.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName-properties "id=IllusionLibs.HoneySelect2.$($_.BaseName);gameVersion=2020.05.29.1;unityVersion=2018.4.11.1"; }
        gci -Path XUnity -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.XUnity.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.XUnity.$($_.BaseName)" }
        gci -Path BepInEx -Filter *.nuspec | foreach { .\GenerateTarget.ps1 "IllusionLibs.BepInEx.$($_.BaseName)" "$($_.DirectoryName)"; nuget pack $_.FullName -properties "id=IllusionLibs.BepInEx.$($_.BaseName)" }
      
    - name: Nuget push
      env:
        NUGET_URL: https://pkgs.dev.azure.com/IllusionMods/Nuget/_packaging/IllusionMods/nuget/v3/index.json
      run: |
        nuget sources add -name "IllusionMods" -src ${env:NUGET_URL} -username "token" -password ${{ secrets.NUGET_TOKEN }}
        nuget push **.nupkg -apikey key -noninteractive -skipduplicate -src ${env:NUGET_URL}
