name: Nuget

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget pack
      run: |
        cd packaging
        .\Build-Packages.ps1
