name: Push to azure nuget feed

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup Azure Artifacts Credential Provider
      run: .\installcredprovider.ps1
      
    - name: Nuget pack
      working-directory: .\packaging
      run: .\Build-Packages.ps1
      
    - name: Nuget push
      run: |
        nuget sources add -name "IllusionMods" -src https://pkgs.dev.azure.com/IllusionMods/Nuget/_packaging/IllusionMods/nuget/v3/index.json -username "token" -password ${{ secrets.NUGET_TOKEN }}
        nuget push **.nupkg -apikey key -noninteractive -skipduplicate -src https://pkgs.dev.azure.com/IllusionMods/Nuget/_packaging/IllusionMods/nuget/v3/index.json
