name: Push to azure nuget feed

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - name: Nuget pack
      working-directory: .\packaging
      run: .\pack.ps1
      
    - name: Nuget push
      env:
        NUGET_URL: https://pkgs.dev.azure.com/IllusionMods/Nuget/_packaging/IllusionMods/nuget/v3/index.json
      run: |
        nuget sources add -name "IllusionMods" -src ${env:NUGET_URL} -username "token" -password ${{ secrets.NUGET_TOKEN }}
        nuget push **.nupkg -apikey key -noninteractive -skipduplicate -src ${env:NUGET_URL}
